### PR TITLE
Please test it before merge!!!

### PR DESCRIPTION
**Pull request by LiorAgnin**

### CODE REVIEW

**Comment by henry-hz** [comment]
Hi @LiorAgnin  just get it. I fetched the merge branch, trying to run, but keep pending after I insert the phone to receive the SMS, I tried in qa and prod modes.


```
I/flutter (29853): Persistor debug: Saving to storage
I/flutter (29853): Persistor debug: Done saving!
I/flutter (29853): │ #0   AppFactory.getLogger.() (package:fusecash/redux/state/store.dart:135:22)
I/flutter (29853): Persistor debug: Done saving!
I/flutter (29853): │ #0   AppFactory.getLogger.() (package:fusecash/redux/state/store.dart:135:22)
I/flutter (29853): │ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter (29853): Persistor debug: Done saving!
I/flutter (29853): │ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter (29853): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (29853): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (29853): │ 👾 [INFO] action: Track - Wallet: user insert his phone number
I/flutter (29853): │ 👾 [INFO] action: Alias - +972548389387
I/flutter (29853): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (29853): Persistor debug: Done saving!
I/flutter (29853): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (29853): Phone number verification failed. Code: firebaseAuth. Message: This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed. Is app running on a physical device? ]

I/flutter (29853): Persistor debug: Starting save...
I/flutter (29853): Persistor debug: Running save transformations
I/flutter (29853): Persistor debug: Serializing
I/flutter (29853): Persistor debug: Running save raw transformations
I/flutter (29853): Persistor debug: Saving to storage
I/flutter (29853): Persistor debug: Starting save...
I/flutter (29853): Persistor debug: Running save transformations
I/flutter (29853): Persistor debug: Serializing
I/flutter (29853): Persistor debug: Running save raw transformations
I/flutter (29853): Persistor debug: Saving to storage
I/flutter (29853): Persistor debug: Done saving!
I/flutter (29853): Persistor debug: Done saving!
```

**Comment by henry-hz** [comment]
@LiorAgnin pls, review our modifications

**Comment by LiorAgnin** [comment]
@henry-hz  LGTM.

**Comment by henry-hz** [comment]
@LiorAgnin ti still keep pending, did you add the SHA1 ? 

```
I/flutter (26571): Phone number verification failed. Code: firebaseAuth. Message: This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed. Is app running on a physical device? ]

```

**Comment by LiorAgnin** [comment]
@henry-hz 
I think it's because of the emulator. can you try with  physical device?

**Comment by henry-hz** [comment]
Interesting, when building the apk, I had an issue with the alias... will make it again
```
* What went wrong:                                                      
Execution failed for task ':app:packageRelease'.                        
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.ide.common.signing.KeytoolException: Failed to read key key from store "/home/henry/wepy-wallet/deploy/my-release-key.keystore": No key with alias 'key' found in keystore /home/henry/wepy-wallet/deploy/my-release-key.keystore
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                     

```

**Comment by LiorAgnin** [comment]
Hi @henry-hz, still having problem?
Let me know if you need any help.

**Comment by henry-hz** [comment]
Thanks @LiorAgnin , but it still keep pending. I am creating a simple firebase from scratch to learn where we need to fix on firebase config

**Comment by henry-hz** [comment]
great !!!

**Pull request merged**
